/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.vistas.instrucciones;

/**
 *
 * @author vinko
 */
public class InstruccUsoPenombres extends javax.swing.JFrame {

    /**
     * Creates new form InstruccUsoPenombres
     */
    public InstruccUsoPenombres() {
        initComponents();
                 setLocationRelativeTo(null);
         this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaInstrucciones = new javax.swing.JScrollPane();
        txtListaInstrucciones = new javax.swing.JTextArea();
        iNSTRUCCIONES = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtListaInstrucciones.setEditable(false);
        txtListaInstrucciones.setColumns(20);
        txtListaInstrucciones.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtListaInstrucciones.setRows(5);
        txtListaInstrucciones.setText("1. ¿Cuál es tu brazo izquierdo?\n2. ¿Cuál es tu brazo derecho?\n3. ¿Cuál es tu mano izquierda?\n4. ¿Cuál es tu mano derecha?\n5. ¿Cuál es tu pierna izquierda?\n6. ¿Cuál es tu pierna derecha?\n7. ¿Cuál es tu ojo izquierdo?\n8. ¿Cuál es tu ojo derecho?\n9. ¿Cuál es tu pie izquierdo?\n10. ¿Cuál es tu pie derecho?\n11. ¿Cuál es tu oreja izquierda?\n12. ¿Cuál es tu oreja derecha?\n\nColoque un objeto (canica) dentro de una caja y sáquelo sucesivamente, alternativamente pregunte al niño:\n\n13. ¿Dónde está la canica?\nRepita 10 veces.\n\nColoque una figura arriba, y después abajo. Alterativamente pregunte:\n14. ¿Dónde está (la imagen)?\nColoque un auto de juguete cerca y lejos del niño, y pregunte:\n15. ¿Dónde está el (auto)?\nColoque un juguete (auto) detrás de un objeto y delante de un objeto; alternativamente pregunte:\n16. ¿Dónde está el (auto)?\nColoque varios objetos de una misma clase en cadena, por ejemplo varios autos. Y pregunte alternadamente al niño:\n17. ¿Cuál es el primero? ¿Cuál es el último?\nRepita 10 veces cada uno de estos ejercicios.\n");
        ListaInstrucciones.setViewportView(txtListaInstrucciones);

        getContentPane().add(ListaInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1130, 640));

        iNSTRUCCIONES.setFont(new java.awt.Font("Dialog", 1, 23)); // NOI18N
        iNSTRUCCIONES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iNSTRUCCIONES.setText("LISTA DE INSTRUCCIONES DE LAS PARTES DEL CUERPO  "); // NOI18N
        iNSTRUCCIONES.setToolTipText("");
        iNSTRUCCIONES.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(iNSTRUCCIONES, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 1130, 30));

        btnVolver.setText("Volver");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, 70, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/FondoRosa.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        UsoPenombres corporal = new UsoPenombres();
        corporal.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstruccUsoPenombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstruccUsoPenombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstruccUsoPenombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstruccUsoPenombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstruccUsoPenombres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JScrollPane ListaInstrucciones;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel iNSTRUCCIONES;
    private javax.swing.JTextArea txtListaInstrucciones;
    // End of variables declaration//GEN-END:variables
}
