/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.vistas.instrucciones;

/**
 *
 * @author lopez
 */
public class ListaPreguntas extends javax.swing.JFrame {
private double estadoPorcentaje;
private double pregunta1;

    /**
     * Creates new form ListaPreguntas
     */
    public ListaPreguntas() {
        initComponents();
         setLocationRelativeTo(null);
         this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogo2 = new javax.swing.JLabel();
        LabelLogo1 = new javax.swing.JLabel();
        txtPregunta27 = new javax.swing.JTextField();
        txtPregunta26 = new javax.swing.JTextField();
        txtPregunta25 = new javax.swing.JTextField();
        txtPregunta24 = new javax.swing.JTextField();
        txtPregunta23 = new javax.swing.JTextField();
        txtPregunta22 = new javax.swing.JTextField();
        txtPregunta21 = new javax.swing.JTextField();
        txtPregunta20 = new javax.swing.JTextField();
        txtPregunta19 = new javax.swing.JTextField();
        txtPregunta18 = new javax.swing.JTextField();
        txtPregunta17 = new javax.swing.JTextField();
        txtPregunta16 = new javax.swing.JTextField();
        txtPregunta15 = new javax.swing.JTextField();
        txtPregunta14 = new javax.swing.JTextField();
        txtPregunta13 = new javax.swing.JTextField();
        txtPregunta12 = new javax.swing.JTextField();
        txtPregunta11 = new javax.swing.JTextField();
        txtPregunta10 = new javax.swing.JTextField();
        txtPregunta9 = new javax.swing.JTextField();
        txtPregunta8 = new javax.swing.JTextField();
        txtPregunta7 = new javax.swing.JTextField();
        txtPregunta6 = new javax.swing.JTextField();
        txtPregunta5 = new javax.swing.JTextField();
        txtPregunta4 = new javax.swing.JTextField();
        txtPregunta3 = new javax.swing.JTextField();
        txtPregunta2 = new javax.swing.JTextField();
        txtPregunta1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/sutspes  en png.png"))); // NOI18N
        getContentPane().add(LabelLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, -1, -1));

        LabelLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/CENTRO DE APOYO EDUCATIVO INFANTIL EN PNG.png"))); // NOI18N
        getContentPane().add(LabelLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtPregunta27.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta27.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta27.setText("27.- ¿A que juegas?");
        txtPregunta27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta27ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta27, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, 310, 40));

        txtPregunta26.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta26.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta26.setText("26.- ¿Juegas con tus amigos?");
        txtPregunta26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta26ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta26, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 310, 40));

        txtPregunta25.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta25.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta25.setText("25.- ¿Como se llaman?");
        txtPregunta25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta25ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 310, 40));

        txtPregunta24.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta24.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta24.setText("24.- ¿Cuantos?");
        txtPregunta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta24ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta24, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 310, 40));

        txtPregunta23.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta23.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta23.setText("23.- ¿Tienes amigos?");
        txtPregunta23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta23ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta23, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 310, 40));

        txtPregunta22.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta22.setText("22.- ¿Con cuáles juegas más?");
        txtPregunta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta22ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta22, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 310, 40));

        txtPregunta21.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta21.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta21.setText("21.- ¿Tienes juguetes?");
        txtPregunta21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta21ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 310, 40));

        txtPregunta20.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta20.setText("20.- ¿Qué te gusta ver en la tv?");
        txtPregunta20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta20ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta20, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 310, 40));

        txtPregunta19.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta19.setText("19.- ¿Tienes televisión en tu casa?");
        txtPregunta19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta19ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta19, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 310, 40));

        txtPregunta18.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta18.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta18.setText("18.- ¿Te gustan los animales?");
        txtPregunta18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta18ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 310, 40));

        txtPregunta17.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta17.setText("17.- ¿Cómo se llaman?");
        txtPregunta17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta17ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 310, 40));

        txtPregunta16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta16.setText("16.- ¿Son más grades o más pequeños?");
        txtPregunta16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta16ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, -1, 40));

        txtPregunta15.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta15.setText("15.- ¿Tienes hermanos?");
        txtPregunta15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta15ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 310, 40));

        txtPregunta14.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta14.setText("14.- ¿Cuál es tu dirección?");
        txtPregunta14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta14ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 310, 40));

        txtPregunta13.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta13.setText("13.- ¿Donde vives?");
        txtPregunta13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta13ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 310, 40));

        txtPregunta12.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta12.setText("12.- ¿Cómo se llama tu papá?");
        txtPregunta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta12ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 310, 40));

        txtPregunta11.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta11.setText("11.- ¿Cómo se llama tu mamá?");
        txtPregunta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta11ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 310, 40));

        txtPregunta10.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta10.setText("10.- ¿Cómo te llamas?");
        txtPregunta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta10ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 310, 40));

        txtPregunta9.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta9.setText("9.- ¿Qué hiciste ayer en la tarde?");
        txtPregunta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta9ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 310, 40));

        txtPregunta8.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta8.setText("8.- ¿Qué desayunaste?");
        txtPregunta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta8ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 310, 40));

        txtPregunta7.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta7.setText("7.- ¿Desayunaste?");
        txtPregunta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 310, 40));

        txtPregunta6.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta6.setText("6.- ¿A qué hora te levantaste hoy?");
        txtPregunta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 310, 40));

        txtPregunta5.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta5.setText("5.- ¿Cómo están tus hermanos?");
        txtPregunta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 310, 40));

        txtPregunta4.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta4.setText("4.- ¿Cómo está tu papá?");
        txtPregunta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 40));

        txtPregunta3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta3.setText("3.- ¿Cómo está tu mamá?");
        txtPregunta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, 40));

        txtPregunta2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta2.setText("2.- ¿Cómo está tu familia?");
        txtPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 40));

        txtPregunta1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        txtPregunta1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPregunta1.setText("1.- ¿Cómo has estado?");
        txtPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPregunta1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/FondoAzul.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void ConcentradoPreguntas(){
    for (int i = 0; i <= 27; i++) {
        
        pregunta1=+pregunta1;
    }
       
    
}
    private void txtPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPregunta1ActionPerformed

    private void txtPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta2ActionPerformed

    private void txtPregunta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta3ActionPerformed

    private void txtPregunta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta4ActionPerformed

    private void txtPregunta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta5ActionPerformed

    private void txtPregunta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta6ActionPerformed

    private void txtPregunta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta7ActionPerformed

    private void txtPregunta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta8ActionPerformed

    private void txtPregunta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta9ActionPerformed

    private void txtPregunta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta10ActionPerformed

    private void txtPregunta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta11ActionPerformed

    private void txtPregunta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta12ActionPerformed

    private void txtPregunta13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta13ActionPerformed

    private void txtPregunta14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta14ActionPerformed

    private void txtPregunta15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta15ActionPerformed

    private void txtPregunta16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta16ActionPerformed

    private void txtPregunta17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta17ActionPerformed

    private void txtPregunta18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta18ActionPerformed

    private void txtPregunta19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta19ActionPerformed

    private void txtPregunta20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta20ActionPerformed

    private void txtPregunta21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta21ActionPerformed

    private void txtPregunta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta22ActionPerformed

    private void txtPregunta23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta23ActionPerformed

    private void txtPregunta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta24ActionPerformed

    private void txtPregunta25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta25ActionPerformed

    private void txtPregunta26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta26ActionPerformed

    private void txtPregunta27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPregunta27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPregunta27ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPreguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelLogo1;
    private javax.swing.JLabel LabelLogo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtPregunta1;
    private javax.swing.JTextField txtPregunta10;
    private javax.swing.JTextField txtPregunta11;
    private javax.swing.JTextField txtPregunta12;
    private javax.swing.JTextField txtPregunta13;
    private javax.swing.JTextField txtPregunta14;
    private javax.swing.JTextField txtPregunta15;
    private javax.swing.JTextField txtPregunta16;
    private javax.swing.JTextField txtPregunta17;
    private javax.swing.JTextField txtPregunta18;
    private javax.swing.JTextField txtPregunta19;
    private javax.swing.JTextField txtPregunta2;
    private javax.swing.JTextField txtPregunta20;
    private javax.swing.JTextField txtPregunta21;
    private javax.swing.JTextField txtPregunta22;
    private javax.swing.JTextField txtPregunta23;
    private javax.swing.JTextField txtPregunta24;
    private javax.swing.JTextField txtPregunta25;
    private javax.swing.JTextField txtPregunta26;
    private javax.swing.JTextField txtPregunta27;
    private javax.swing.JTextField txtPregunta3;
    private javax.swing.JTextField txtPregunta4;
    private javax.swing.JTextField txtPregunta5;
    private javax.swing.JTextField txtPregunta6;
    private javax.swing.JTextField txtPregunta7;
    private javax.swing.JTextField txtPregunta8;
    private javax.swing.JTextField txtPregunta9;
    // End of variables declaration//GEN-END:variables
}
