
package mx.itson.vistas;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mx.itson.controlador.DBHelper;
import mx.itson.entidades.*;
import mx.itson.interfaces.*;

/**
 *
 * @author jotha
 */
public class MostrarNiño extends javax.swing.JFrame {

    /**
     * Creates new form EditarTerapeuta
     */
    public MostrarNiño() {
        initComponents();
        VerNiños vn = new VerNiños();
        lbl_id.setText(vn.idNiño + "");
        RefrescarTerapeutas();
        setLocationRelativeTo(null);
        
        
    }
    
    private void RefrescarTerapeutas(){
        
        VerNiños vn = new VerNiños();
        DAOAlumnoIMP dao = new DAOAlumnoIMP();
        
        try {
            Alumno alumno = dao.obtenerPorId(vn.idNiño);
            lbl_nombre.setText(alumno.getNombre());
            lbl_Edad.setText(alumno.getEdad()+"");
            lbl_Nivel.setText(alumno.getNivel());
            lbl_NombreTutor.setText(alumno.getNombreTutor());
            lbl_Telefono.setText(alumno.getTelefono());
            
            try {
                
                Connection cn = DBHelper.conectar() ;
                PreparedStatement pst = cn.prepareStatement("SELECT * FROM sutspes.niños WHERE idNiño = " + vn.idNiño);
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    //leer Binario
                    Blob blob = rs.getBlob(7);
                    //pasar el binario a imagen
                    byte[] data = blob.getBytes(1, (int) blob.length());
                    //lee la imagen
                    BufferedImage img = null;
                    try {
                        img = ImageIO.read(new ByteArrayInputStream(data));
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    
                    ImageIcon icono = new ImageIcon(img);
                    Icon imagen = new ImageIcon(icono.getImage().getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT));
                    lbl_imagen.setIcon(imagen);
                }
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "¡Error al cargar!");
                System.out.println("Error al cargar foto: " + e);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_volver = new javax.swing.JLabel();
        lbl_imagen = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_tID = new javax.swing.JLabel();
        lbl_tEmail = new javax.swing.JLabel();
        lbl_tNombreTutor = new javax.swing.JLabel();
        lbl_tArea = new javax.swing.JLabel();
        lbl_Edad = new javax.swing.JLabel();
        lbl_Nivel = new javax.swing.JLabel();
        lbl_NombreTutor = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_tNombre1 = new javax.swing.JLabel();
        lbl_tTelefono = new javax.swing.JLabel();
        lbl_Telefono = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/atras amarillo.png"))); // NOI18N
        lbl_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_volverMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        lbl_imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_imagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 360));

        lbl_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        lbl_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 30, 30));

        lbl_tID.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tID.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tID.setText("Su id es:");
        getContentPane().add(lbl_tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        lbl_tEmail.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tEmail.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tEmail.setText("Nivel:");
        getContentPane().add(lbl_tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        lbl_tNombreTutor.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tNombreTutor.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tNombreTutor.setText("Tutor:");
        getContentPane().add(lbl_tNombreTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 40));

        lbl_tArea.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tArea.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tArea.setText("Edad:");
        getContentPane().add(lbl_tArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        lbl_Edad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Edad.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Edad.setText("jLabel1");
        lbl_Edad.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, 40));

        lbl_Nivel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Nivel.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Nivel.setText("jLabel1");
        lbl_Nivel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_Nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, 40));

        lbl_NombreTutor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_NombreTutor.setForeground(new java.awt.Color(0, 0, 0));
        lbl_NombreTutor.setText("jLabel1");
        lbl_NombreTutor.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_NombreTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, 40));

        lbl_nombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombre.setText("jLabel1");
        lbl_nombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, 40));

        lbl_tNombre1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tNombre1.setText("Nombre:");
        getContentPane().add(lbl_tNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        lbl_tTelefono.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tTelefono.setText("Telefono:");
        getContentPane().add(lbl_tTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, 40));

        lbl_Telefono.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Telefono.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Telefono.setText("jLabel1");
        lbl_Telefono.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/FondoAmarillo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 910, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_volverMouseClicked
        VerTerapeutas vt = new VerTerapeutas();
        vt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_volverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarNiño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarNiño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel lbl_Edad;
    private javax.swing.JLabel lbl_Nivel;
    private javax.swing.JLabel lbl_NombreTutor;
    private javax.swing.JLabel lbl_Telefono;
    private javax.swing.JLabel lbl_id;
    public javax.swing.JLabel lbl_imagen;
    public javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tArea;
    private javax.swing.JLabel lbl_tEmail;
    private javax.swing.JLabel lbl_tID;
    private javax.swing.JLabel lbl_tNombre1;
    private javax.swing.JLabel lbl_tNombreTutor;
    private javax.swing.JLabel lbl_tTelefono;
    private javax.swing.JLabel lbl_volver;
    // End of variables declaration//GEN-END:variables
}
