
package mx.itson.vistas;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import mx.itson.controlador.DBHelper;
import mx.itson.entidades.*;
import mx.itson.interfaces.*;

/**
 *
 * @author jotha
 */
public class MostrarTerapeuta extends javax.swing.JFrame {

    /**
     * Creates new form EditarTerapeuta
     */
    public MostrarTerapeuta() {
        initComponents();
        DAOTerapeutaIMP dao = new DAOTerapeutaIMP();
        VerTerapeutas vt = new VerTerapeutas();
        lbl_id.setText(vt.idEdit + "");
        RefrescarTerapeutas();
        
        
    }
    
    private void RefrescarTerapeutas(){
        
        AgregarTerapeuta at = new AgregarTerapeuta();
        VerTerapeutas vt = new VerTerapeutas();
        DAOTerapeutaIMP dao = new DAOTerapeutaIMP();
        
        try {
            Terapeuta terapeuta = dao.obtenerPorId(vt.idEdit);
            lbl_nombre.setText(terapeuta.getNombre());
            lbl_area.setText(terapeuta.getPuesto());
            lbl_email.setText(terapeuta.getCorreo());
            lbl_usuario.setText(terapeuta.getCodigoUsuario());
            
            try {
                
                Connection cn = DBHelper.conectar() ;
                PreparedStatement pst = cn.prepareStatement("SELECT * FROM bxopxuzsnsc4au7ggfnf.terapeuta WHERE IdTerap = " + 10);
                ResultSet rs = pst.executeQuery();
                
                if(rs.next()){
                    //leer Binario
                    Blob blob = rs.getBlob(8);
                    //pasar el binario a imagen
                    byte[] data = blob.getBytes(1, (int) blob.length());
                    //lee la imagen
                    BufferedImage img = null;
                    try {
                        img = ImageIO.read(new ByteArrayInputStream(data));
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    
                    ImageIcon icono = new ImageIcon(img);
                    Icon imagen = new ImageIcon(icono.getImage().getScaledInstance(lbl_imagen.getWidth(), lbl_imagen.getHeight(), Image.SCALE_DEFAULT));
                    lbl_imagen.setIcon(imagen);
                }
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "¡Error al cargar!");
                System.out.println("Error al cargar foto: " + e);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverMenu = new javax.swing.JLabel();
        lbl_volver = new javax.swing.JLabel();
        lbl_imagen = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        lbl_tID = new javax.swing.JLabel();
        lbl_tEmail = new javax.swing.JLabel();
        lbl_tUsuario = new javax.swing.JLabel();
        lbl_tArea = new javax.swing.JLabel();
        lbl_area = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_tNombre1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/atras.png"))); // NOI18N
        btnVolverMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnVolverMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, -1, -1));

        lbl_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/atras amarillo.png"))); // NOI18N
        lbl_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_volverMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 70));

        lbl_imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbl_imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_imagen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 350, 360));

        lbl_id.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        lbl_id.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 30, 30));

        lbl_tID.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tID.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tID.setText("Su id es:");
        getContentPane().add(lbl_tID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        lbl_tEmail.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tEmail.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tEmail.setText("Email:");
        getContentPane().add(lbl_tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        lbl_tUsuario.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tUsuario.setText("Usuario:");
        getContentPane().add(lbl_tUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, 40));

        lbl_tArea.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tArea.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tArea.setText("Area:");
        getContentPane().add(lbl_tArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        lbl_area.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_area.setForeground(new java.awt.Color(0, 0, 0));
        lbl_area.setText("jLabel1");
        lbl_area.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, 40));

        lbl_email.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("jLabel1");
        lbl_email.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, 40));

        lbl_usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(0, 0, 0));
        lbl_usuario.setText("jLabel1");
        lbl_usuario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, 40));

        lbl_nombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombre.setText("jLabel1");
        lbl_nombre.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, 40));

        lbl_tNombre1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        lbl_tNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tNombre1.setText("Nombre:");
        getContentPane().add(lbl_tNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mx/itson/imagenes/FondoAmarillo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 910, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_volverMouseClicked
        VerTerapeutas vt = new VerTerapeutas();
        vt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbl_volverMouseClicked

    private void btnVolverMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuMouseClicked
        Menu VolverMenu = new Menu();
        VolverMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTerapeuta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTerapeuta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel btnVolverMenu;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_id;
    public javax.swing.JLabel lbl_imagen;
    public javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tArea;
    private javax.swing.JLabel lbl_tEmail;
    private javax.swing.JLabel lbl_tID;
    private javax.swing.JLabel lbl_tNombre1;
    private javax.swing.JLabel lbl_tUsuario;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_volver;
    // End of variables declaration//GEN-END:variables
}
